
const notesData = [
  {
    id: 'notes-1',
    title: "Belajar Laravel - PORTODIT",
    body: "Laravel adalah framework PHP yang mempermudah pengembangan aplikasi web dengan menyediakan berbagai fitur yang powerful.\n\nNama Penulis: I Putu Adhitya Pratama M",
    archived: false,
    category: "Laravel",
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notes-2',
    title: "Pengenalan React JS - PORTODIT",
    body: "React JS adalah library JavaScript untuk membangun antarmuka pengguna yang interaktif dan cepat.\n\nNama Penulis: I Putu Adhitya Pratama M",
    archived: false,
    category: "React JS",
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notes-3',
    title: "Dasar-Dasar Kotlin - PORTODIT",
    body: "Kotlin adalah bahasa pemrograman yang berjalan di JVM dan merupakan alternatif modern untuk Java dalam pengembangan aplikasi Android.\n\nNama Penulis: I Putu Adhitya Pratama M",
    archived: true,
    category: "Kotlin",
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notes-4',
    title: "Manajemen State di React JS - PORTODIT",
    body: "State di React digunakan untuk mengelola data dinamis yang dapat berubah seiring interaksi pengguna.\n\nNama Penulis: I Putu Adhitya Pratama M",
    archived: false,
    category: "React JS",
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notes-5',
    title: "Routing di Laravel - PORTODIT",
    body: "Laravel menyediakan sistem routing yang fleksibel dan mudah digunakan untuk mengatur jalur aplikasi web.\n\nNama Penulis: I Putu Adhitya Pratama M",
    archived: false,
    category: "Laravel",
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notes-6',
    title: "Kotlin Coroutines - PORTODIT",
    body: "Coroutines di Kotlin memungkinkan penanganan tugas-tugas asinkron dengan cara yang lebih efisien dan sederhana.\n\nNama Penulis: I Putu Adhitya Pratama M",
    archived: false,
    category: "Kotlin",
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notes-7',
    title: "Komponen dalam React JS - PORTODIT",
    body: "Komponen di React adalah blok bangunan aplikasi, memungkinkan pembuatan antarmuka pengguna yang terstruktur dan dapat digunakan kembali.\n\nNama Penulis: I Putu Adhitya Pratama M",
    archived: true,
    category: "React JS",
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notes-8',
    title: "Migrations di Laravel - PORTODIT",
    body: "Laravel menyediakan fitur migrations untuk mengelola perubahan skema database dengan mudah dan terstruktur.\n\nNama Penulis: I Putu Adhitya Pratama M",
    archived: false,
    category: "Laravel",
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notes-9',
    title: "Extension di Kotlin - PORTODIT",
    body: "Kotlin mendukung ekstensi fungsi dan properti untuk memperluas kemampuan kelas tanpa harus mengubah kode kelas tersebut.\n\nNama Penulis: I Putu Adhitya Pratama M",
    archived: false,
    category: "Kotlin",
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notes-10',
    title: "Testing di Laravel - PORTODIT",
    body: "Laravel memiliki sistem testing yang kuat dan mendukung berbagai metode testing untuk memastikan kualitas aplikasi.\n\nNama Penulis: I Putu Adhitya Pratama M",
    archived: false,
    category: "Laravel",
    createdAt: new Date().toISOString(),
  },
];

export default notesData;
